"""
Url mappings for the recipe app.
"""
# define a path and include urls by there url names
from django.urls import (
	path,
	include,
)
# provided by DRF and can be used with an API view to automatically create routes for all of the different options available for the view
from rest_framework.routers import DefaultRouter

from recipe import views

router = DefaultRouter()
# this will create an endpoint /recipes/ and assign all our endpoints from our recipe view set to that endpoint.
# which basically mean it will have auto generate url based on the functionality of the viewset
# because we are using the model view set it going to support allof the available method (Create, read, update and delete)
router.register('recipes', views.RecipeViewSet)
# define app name which is used for the reverse lookup urls
app_name = 'recipe'
# inlude all of the url generated by the router
urlpatterns = [
	path('', include(router.urls))
]